matrix:
  include:
    - os: linux
      sudo: required
    - os: osx
      sudo: required
  allow_failures:
    - os: linux

addon:
  apt:
    packages:
      r-base-core

after_success:
  - Rscript -e 'library(covr); covr::codecov()'

before_install:
  - export HOMEBREW_NO_AUTO_UPDATE=1
  - export HOMEBREW_DEVELOPER=1
  - export HOMEBREW_FORCE_VENDOR_RUBY=1
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      FORMULA="libbi";
      brew update;
      brew cask uninstall --force oclint;
      brew tap sbfnk/libbi;
      curl https://cran.rstudio.com/bin/macosx/R-3.4.3.pkg -o R.pkg;
      sudo installer -pkg R.pkg -target /;
    fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo apt-get -qq update;
      sudo apt-get install -y libxml2-dev;
      LINUXBREW="/home/linuxbrew/.linuxbrew"
      FORMULA="libbi-linux";
      export PATH="$LINUXBREW/bin:$LINUXBREW/sbin:$PATH";
      sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)";
      brew tap sbfnk/libbi;
      chmod 644 $LINUXBREW/Homebrew/Library/Taps/sbfnk/homebrew-libbi/"$FORMULA".rb;
    fi
  - brew install sbfnk/libbi/$FORMULA; true
  - echo 'options(repos=structure(c(CRAN="https://cloud.r-project.org/")))' > ~/.Rprofile
  - R -e 'install.packages("devtools")'

install: 
  - R -e 'devtools::install_deps(dep = T)'

script:
  - R CMD build .
  - R CMD check *.tar.gz


