language: r
cache: packages
warnings_are_errors: false

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: linux

env:
  - NOT_CRAN=true

before_install:
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      sudo chown -R $USER $(brew --repo);
      brew update
      mkdir -p $(brew --repo)/Library/Taps
      ln -s $PWD $(brew --repo)/Library/Taps/travis-testtap
      brew tap --repair;
      brew tap homebrew/science;
      brew update;
    fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo mkdir -p /home/linuxbrew;
      sudo chown "$USER" /home/linuxbrew;
      LINUXBREW=/home/linuxbrew/.linuxbrew;
      git clone https://github.com/Linuxbrew/brew.git "$LINUXBREW";
      export PATH="$LINUXBREW/bin:$PATH";
      export LD_LIBRARY_PATH=$(echo $LD_LIBRARY_PATH | sed 's/:$//');
      brew tap homebrew/science;
      brew tap sbfnk/libbi;
      brew install gcc;
      brew install curl --with-libidn;
      brew install cmake --with-libidn;
      brew install --without-test sbfnk/libbi/libbi;
      env;
    fi

brew_packages:
  - homebrew/science/libbi

