matrix:
  include:
    - os: linux
      sudo: required
    - os: osx
      sudo: required
  allow_failures:
    - os: linux

after_success:
  - Rscript -e 'library(covr); covr::codecov()'

before_install:
  - export HOMEBREW_NO_AUTO_UPDATE=1
  - export HOMEBREW_DEVELOPER=1
  - export HOMEBREW_FORCE_VENDOR_RUBY=1
  - export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH";
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      FORMULA="libbi";
      brew cask uninstall --force oclint;
      brew tap sbfnk/libbi;
      curl https://cran.rstudio.com/bin/macosx/R-3.4.3.pkg
      sudo installer -pkg R-3.2.3.pkg -target /
      R -e 'Sys.getenv()';
    fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)";
      LINUXBREW="/home/linuxbrew/.linuxbrew"
      FORMULA="libbi-linux";
      export PATH="$LINUXBREW/bin:$LINUXBREW/sbin:$PATH";
      brew tap sbfnk/libbi;
      chmod 644 $LINUXBREW/Homebrew/Library/Taps/sbfnk/homebrew-libbi/"$FORMULA".rb;
      /bin/rm /home/travis/R-bin/lib/libcurl* /home/travis/R-bin/lib/libz.*;
    fi
  - brew install sbfnk/libbi/$FORMULA; true
  - R -e 'install.packages("devtools")'

install: 
  - R -e 'devtools::install_deps(dep = T)'

script:
  - R CMD build .
  - R CMD check *.tar.gz


