language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
  allow_failures:
    - os: linux

r_binary_packages:
  - magrittr
  - lazyeval
  - mime
  - curl
  - openssl
  - R6
  - jsonlite
  - httr
  - crayon
  - reshape2
  - ncdf4
  - data.table
  - coda
  - testthat
  - digest
  - praise
  - R.rsp
  - covr
  - knitr

after_success:
  - Rscript -e 'library(covr); covr::codecov()'

before_install:
  - export HOMEBREW_NO_AUTO_UPDATE=1
  - export HOMEBREW_DEVELOPER=1
  - export HOMEBREW_FORCE_VENDOR_RUBY=1
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew cask uninstall --force oclint;
      brew tap sbfnk/libbi;
      brew install libbi;
      mkdir -p ~/.R;
      echo "Q0M9L3Vzci9sb2NhbC9vcHQvbGx2bS9iaW4vY2xhbmcgLWZvcGVubXAKQ1hYPS91c3IvbG9jYWwvb3B0L2xsdm0vYmluL2NsYW5nKysKQ0ZMQUdTPS1nIC1PMyAtV2FsbCAtcGVkYW50aWMgLXN0ZD1nbnU5OSAtbXR1bmU9bmF0aXZlIC1waXBlCkNYWEZMQUdTPS1nIC1PMyAtV2FsbCAtcGVkYW50aWMgLXN0ZD1jKysxMSAtbXR1bmU9bmF0aXZlIC1waXBlCkxERkxBR1M9LUwvdXNyL2xvY2FsL29wdC9nZXR0ZXh0L2xpYiAtTC91c3IvbG9jYWwvb3B0L2xsdm0vbGliIC1XbCwtcnBhdGgsL3Vzci9sb2NhbC9vcHQvbGx2bS9saWIKQ1BQRkxBR1M9LUkvdXNyL2xvY2FsL29wdC9nZXR0ZXh0L2luY2x1ZGUgLUkvdXNyL2xvY2FsL29wdC9sbHZtL2luY2x1ZGU=" | base64 -D > ~/.R/Makevars;
    fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo mkdir -p /home/linuxbrew;
      sudo chown "$USER" /home/linuxbrew;
      LINUXBREW=/home/linuxbrew/.linuxbrew;
      git clone https://github.com/Linuxbrew/brew.git "$LINUXBREW";
      export PATH="$LINUXBREW/bin:$PATH";
      exprt LD_LIBRARY_PATH="$LINUXBREW/lib:$LD_LIBRARY_PATH";
      export CPPFLAGS="-I$LINUXBREW/include $CPPFLAGS";
      export LDFLAGS="-L$LINUXBREW/lib $LDFLAGS";
      brew tap sbfnk/libbi;
      chmod 644 /home/linuxbrew/.linuxbrew/Library/Taps/sbfnk/homebrew-libbi/libbi.rb;
      brew install libbi;
      mkdir -p ~/.R;
    fi

