language: r
cache: packages
warnings_are_errors: false

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr); covr::codecov()'

before_install:
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      sudo chown -R $USER $(brew --repo);
      brew update
      mkdir -p $(brew --repo)/Library/Taps
      ln -s $PWD $(brew --repo)/Library/Taps/travis-testtap
      brew tap --repair;
      brew tap homebrew/science;
      brew update;
    fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      git clone https://github.com/Linuxbrew/brew.git ~/.linuxbrew;
      echo "$LD_LIBRARY_PATH";
      export PATH="$HOME/.linuxbrew/bin:$PATH";
      echo "$LD_LIBRARY_PATH";
      brew tap homebrew/science;
      echo "$LD_LIBRARY_PATH";
      brew install homebrew/science/libbi;
      echo "$LD_LIBRARY_PATH";
    fi

brew_packages:
  - homebrew/science/libbi

apt_packages:
  - libnetcdf-dev
  - netcdf-bin
