language: r
cache: packages

matrix:
  include:
    - os: linux
      sudo: required
    - os: osx
  allow_failures:
    - os: linux

after_success:
  - Rscript -e 'library(covr); covr::codecov()'

before_install:
  - export HOMEBREW_NO_AUTO_UPDATE=1
  - export HOMEBREW_DEVELOPER=1
  - export HOMEBREW_FORCE_VENDOR_RUBY=1
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      FORMULA="libbi";
      brew cask uninstall --force oclint;
      brew tap sbfnk/libbi;
    fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      LINUXBREW="/home/linuxbrew/.linuxbrew";
      export PATH="$LINUXBREW/bin:$LINUXBREW/sbin:$PATH";
      sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)";
      FORMULA="libbi-linux";
      brew install libgcrypt libssh2 icu4c r;
      R -e 'install.packages("devtools", repos="http://cran.rstudio.com/")';
      brew tap sbfnk/libbi;
      chmod 644 $LINUXBREW/Homebrew/Library/Taps/sbfnk/homebrew-libbi/"$FORMULA".rb;
      Rscript -e 'devtools::install_deps(dependencies = TRUE)';
      fi
  - brew install sbfnk/libbi/$FORMULA; true
  - which R
  - env
  - R -e 'Sys.getenv()'
